# Generated by Django 2.2 on 2020-11-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(blank=True, max_length=100)),
                ('sport', models.CharField(blank=True, max_length=100)),
                ('person', models.CharField(blank=True, max_length=100)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('adjective', models.CharField(blank=True, max_length=100)),
                ('place', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('athlete', models.CharField(blank=True, max_length=100)),
                ('expression', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
